version: '3'

services:

  app:
    restart: always
    env_file: .env.compose
    build: .
    depends_on:
      - db
    ports:
      - '8080:8080'

  db:
    restart: always
    env_file: .env.compose
    image: postgres:latest
    volumes:
      - .pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
