# Generated by Django 3.0.3 on 2020-03-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='account_from_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='account_from_currency',
            field=models.CharField(choices=[('USD', 'Usd'), ('EUR', 'Eur'), ('CNY', 'Cny')], default='USD', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='account_from_uuid',
            field=models.UUIDField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='account_to_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='account_to_currency',
            field=models.CharField(choices=[('USD', 'Usd'), ('EUR', 'Eur'), ('CNY', 'Cny')], default='USD', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='account_to_uuid',
            field=models.UUIDField(default=None),
            preserve_default=False,
        ),
    ]
